export { Hero } from "./Hero";
export { Diferenciais } from "./Diferenciais";
export { Depoimentos } from "./Depoimentos";
export { OQueEPilates } from "./OQueEPilates";
export { ConhecaStudio } from "./ConhecaStudio";
export { GoogleReviews } from "./GoogleReviews";
export { Agendamento } from "./Agendamento";
export { CTAFinal } from "./CTAFinal";
export { Footer } from "./Footer";
